language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: esiFqdIoxSkTfBnYSoolpenpke3ndYqmOMu/ymSynlZdcopneN60urZ7e+twHPECbXomJPoLuhFthiNe12oN0+Rw6Z2v3K6x7k5Qn/hyzAr5RILs8q0QDqaJP7FnROT2PRyy5SxJfOIZPj9e5SPQF2TCdKKiGahkQ/9bOZEH3Lrt/+RyV1ihd5msX2bKbsTyeI/PzFqH5us+H84MuI0Q9E2/+hQt83xo03PNQT8OjWiOlnM7i0bFyVnfwvqK64PQMmHLfO4ZGpTD5sgjAqPz6ieiYcKi39aoOsk8J6XmvBkvnTvtBMAhHAx9BJXe2t+FBfJDyfmbIsRLgqqRJqxQrgMe2WrwTbcdfDMr5xGcKdKA8eupIvsPcVItBWistpsX3PWbOCnnIRsdf76BuBKIuWjnAxayuHYG9Uc8ju+ygwJj0TL9mPEwKc8IYmaywjQBUpStk0ljZAoj3iNEjXRiATPbysqmB8VMMte2K0KET6dlNuYN5Y83jsiFPVnu1yAOddgsUYF02MZMO/DMStToAt+7ZNTEM2zJ106qnZtGpCm1QCkoEPTGhL4wimkBmuZ00NBNGxQmMsUcT90CPuayefEklu1NlqFaUg5P5SPe63gVk1+qDjvgk6minzDcYuOi27THsbq4duCYNV8Xm2HgJvjB0dqg5PX9eZyDDq36GM8=
  app: balzua-game-deck-server
  on:
    repo: balzua/game-deck-server
